workflows:
  urgent:
    name: URGENT BUILD
    environment:
      node: 18
    scripts:
      - name: BUILD NOW
        script: |
          echo "🚨 EMERGENCY BUILD STARTED"
          npm install
          npx expo prebuild --platform android
          cd android
          ./gradlew assembleDebug
          echo "✅ BUILD SUCCESS - APK READY"
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - maisabbas445@gmail.com
