workflows:
  emergency:
    name: بناء طارئ
    project_directory: Simply-AI-mais-abbas-  # ⭐ السطر الأهم ⭐
    environment:
      node: 18
    scripts:
      - name: بناء سريع
        script: |
          cd Simply-AI-mais-abbas-
          npm install
          npx expo prebuild --platform android
          cd android && ./gradlew assembleDebug
    artifacts:
      - Simply-AI-mais-abbas-/android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - maisabbas445@gmail.com
